version: "3"
services:
  api:
    build: ./services/api/shoeroom-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: shoeroom-api
  client:
    build: ./services/client/my-app
    ports:
      - "80:80"
    container_name: shoeroom-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: shoeroom-db